# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [main]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Test
      env:  
        username_text: ${{ secrets.USERNAME_TEXT }}
        password_text : ${{ secrets.PASSWORD_TEXT }}
      run: python test.py
