# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Python-TEST

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # Also trigger on page_build, as well as release created events
  page_build:
  release:
    types: # This configuration does not affect the page_build event above
      - created
    
jobs:
  TEST:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    
    
    - name: Prepare 
      # https://github.com/marketplace/actions/setup-chromedriver
      uses: nanasess/setup-chromedriver@master
    - name: Launch browser
      run: |
        
        pip install selenium
        pip install configparser
        google-chrome --version
        export DISPLAY=:99
        chromedriver --url-base=/wd/hub &
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional, disables headless mode
            - name: Working
      env:  
        USERNAME_TEXT: ${{ secrets.USERNAME_TEXT }}
        PASSWORD_TEXT: ${{ secrets.PASSWORD_TEXT }}
        SERVERPUSHKEY: ${{ secrets.SERVERPUSHKEY }}
        MSG_TO: ${{ secrets.MSG_TO }}
      run: python test.py
      
