# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: 运行

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  schedule:
    - cron: '10 3 * * *'
    - cron: '10 11 * * *'

    
jobs:
  TEST:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Working
      env:  
        USERNAME_TEXT: ${{ secrets.USERNAME_TEXT }}
        PASSWORD_TEXT: ${{ secrets.PASSWORD_TEXT }}
        SERVERPUSHKEY: ${{ secrets.SERVERPUSHKEY }}
        MSG_TO: ${{ secrets.MSG_TO }}
      run: python test.py
      
